version: "3.9"

services:
  db:
    container_name: db
    image: postgres:16rc1
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_test
      PGUSER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_test"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app_todo

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: "always"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - app_todo
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_todo
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db_test?schema=public
      PORT: 4000

networks:
  app_todo:
    name: app_todo_network
